version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: senha123
      POSTGRES_USER: devtaskmanager
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data